# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        MainWindow.setMaximumSize(QtCore.QSize(600, 450))
        MainWindow.setBaseSize(QtCore.QSize(600, 450))
        font = QtGui.QFont()
        font.setFamily(":/assets/fonts/sub_font.ttf")
        font.setPointSize(20)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/images/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: rgb(10, 10, 10);\n"
"     font-family: \":/assets/fonts/sub_font.ttf\";\n"
"    font-size: 20pt;\n"
"    color: rgb(52, 0, 222);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: rgb(52, 0, 222);\n"
"    border: 1px solid rgb(131, 30, 232);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: gray;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: rgb(10, 10, 10);\n"
"    color: rgb(52, 0, 222);\n"
"    border: 1px solid rgb(131, 30, 232);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: rgb(52, 0, 222);\n"
"    border: 1px solid rgb(131, 30, 232);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: rgb(52, 0, 222);\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid rgb(131, 30, 232);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: rgb(10, 10, 10);\n"
"    color: rgb(52, 0, 222);\n"
"    border: 1px solid rgb(131, 30, 232);\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    color: rgb(255, 255, 255);\n"
"    text-align: center;\n"
"    font-family: \":/assets/fonts/main_font.ttf\";\n"
"    font-size: 28px;\n"
"    background: rgb(10, 10, 10);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3400de, stop:1 #831ee8);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(10, 10, 10);\n"
"    selection-background-color: rgb(52, 0, 222);\n"
"    selection-color: rgb(10, 10, 10);\n"
"    color: rgb(52, 0, 222);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgb(10, 10, 10);\n"
"    font-family: \":/assets/fonts/sub_font.ttf\";\n"
"    font-size: 18pt;\n"
"    color: rgb(52, 0, 222);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoHorizontalLayout = QtWidgets.QHBoxLayout()
        self.logoHorizontalLayout.setObjectName("logoHorizontalLayout")
        self.logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo.setMaximumSize(QtCore.QSize(256, 92))
        self.logo.setMouseTracking(False)
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/assets/images/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.logoHorizontalLayout.addWidget(self.logo)
        self.verticalLayout.addLayout(self.logoHorizontalLayout)
        self.username = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setStyleSheet("font-family: \":/assets/fonts/mian_font.ttf\";\n"
"")
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.start_progress = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.start_progress.setStyleSheet("font: 22pt \"sub_font\";")
        self.start_progress.setProperty("value", 0)
        self.start_progress.setObjectName("start_progress")
        self.verticalLayout.addWidget(self.start_progress)
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout.addWidget(self.start_button)
        self.tab_widget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_widget.setObjectName("tab_widget")
        self.vanila_tab = QtWidgets.QWidget()
        self.vanila_tab.setObjectName("vanila_tab")
        self.vanila_layout = QtWidgets.QVBoxLayout(self.vanila_tab)
        self.vanila_layout.setObjectName("vanila_layout")
        self.vanilla_combobox = QtWidgets.QComboBox(parent=self.vanila_tab)
        self.vanilla_combobox.setObjectName("vanilla_combobox")
        self.vanila_layout.addWidget(self.vanilla_combobox)
        self.tab_widget.addTab(self.vanila_tab, "")
        self.forge_tab = QtWidgets.QWidget()
        self.forge_tab.setObjectName("forge_tab")
        self.forge_layout = QtWidgets.QVBoxLayout(self.forge_tab)
        self.forge_layout.setObjectName("forge_layout")
        self.forge_combobox = QtWidgets.QComboBox(parent=self.forge_tab)
        self.forge_combobox.setObjectName("forge_combobox")
        self.forge_layout.addWidget(self.forge_combobox)
        self.tab_widget.addTab(self.forge_tab, "")
        self.fabric_tab = QtWidgets.QWidget()
        self.fabric_tab.setObjectName("fabric_tab")
        self.fabric_layout = QtWidgets.QVBoxLayout(self.fabric_tab)
        self.fabric_layout.setObjectName("fabric_layout")
        self.fabric_combobox = QtWidgets.QComboBox(parent=self.fabric_tab)
        self.fabric_combobox.setObjectName("fabric_combobox")
        self.fabric_layout.addWidget(self.fabric_combobox)
        self.tab_widget.addTab(self.fabric_tab, "")
        self.quilt_tab = QtWidgets.QWidget()
        self.quilt_tab.setObjectName("quilt_tab")
        self.quilt_layout = QtWidgets.QVBoxLayout(self.quilt_tab)
        self.quilt_layout.setObjectName("quilt_layout")
        self.quilt_combobox = QtWidgets.QComboBox(parent=self.quilt_tab)
        self.quilt_combobox.setObjectName("quilt_combobox")
        self.quilt_layout.addWidget(self.quilt_combobox)
        self.tab_widget.addTab(self.quilt_tab, "")
        self.installed_tab = QtWidgets.QWidget()
        self.installed_tab.setObjectName("installed_tab")
        self.installed_layout = QtWidgets.QVBoxLayout(self.installed_tab)
        self.installed_layout.setObjectName("installed_layout")
        self.installed_combobox = QtWidgets.QComboBox(parent=self.installed_tab)
        self.installed_combobox.setObjectName("installed_combobox")
        self.installed_layout.addWidget(self.installed_combobox)
        self.installed_search = QtWidgets.QLineEdit(parent=self.installed_tab)
        self.installed_search.setObjectName("installed_search")
        self.installed_layout.addWidget(self.installed_search)
        self.tab_widget.addTab(self.installed_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.settings_layout = QtWidgets.QVBoxLayout(self.settings_tab)
        self.settings_layout.setObjectName("settings_layout")
        self.theme_combobox = QtWidgets.QComboBox(parent=self.settings_tab)
        self.theme_combobox.setObjectName("theme_combobox")
        self.settings_layout.addWidget(self.theme_combobox)
        self.tab_widget.addTab(self.settings_tab, "")
        self.verticalLayout.addWidget(self.tab_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pit Launcher"))
        self.username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.start_button.setText(_translate("MainWindow", "Play"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.vanila_tab), _translate("MainWindow", "Vanilla"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.forge_tab), _translate("MainWindow", "Forge"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.fabric_tab), _translate("MainWindow", "Fabric"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.quilt_tab), _translate("MainWindow", "Quilt"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.installed_tab), _translate("MainWindow", "Installed"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.settings_tab), _translate("MainWindow", "Theme"))
